---
include:
  - board: corne_kb_right
    shield: nice_view
  - board: corne_kb_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    #  reset
  - board: corne_kb_left
    shield: settings_reset
  - board: corne_kb_right
    shield: settings_reset
 
